const GAME_DATA = {
    'Films': [
        { word: 'TITANIC', trivia: 'Titanic was the first film to gross over $1 billion worldwide and held the box office record for twelve years.' },
        { word: 'AVATAR', trivia: 'Avatar is the highest-grossing film of all time, using groundbreaking motion-capture technology to create the alien world of Pandora.' },
        { word: 'INCEPTION', trivia: 'Christopher Nolan wrote the script for Inception over ten years, creating one of cinema\'s most intricate and mind-bending narratives.' },
        { word: 'GLADIATOR', trivia: 'Russell Crowe\'s wounds in the opening battle scene were real, and the film won five Academy Awards including Best Picture.' },
        { word: 'JOKER', trivia: 'Joaquin Phoenix lost fifty-two pounds for his transformative role as Arthur Fleck, earning him an Academy Award for Best Actor.' },
        { word: 'INTERSTELLAR', trivia: 'Interstellar consulted physicist Kip Thorne to ensure scientific accuracy in depicting black holes and space-time relativity throughout the film.' },
        { word: 'MATRIX', trivia: 'The falling code in The Matrix actually comes from sushi recipes, and the film revolutionized action cinema with bullet-time effects.' },
        { word: 'GODFATHER', trivia: 'The cat in Marlon Brando\'s lap during the opening scene was a stray found on the Paramount lot that morning.' },
        { word: 'PARASITE', trivia: 'Parasite was the first non-English language film to win Best Picture at the Oscars, sweeping four major Academy Awards.' },
        { word: 'FROZEN', trivia: 'Elsa was originally conceived as the villain of Frozen, but the song "Let It Go" transformed her into a protagonist.' },
        { word: 'UP', trivia: 'Up was the second animated film nominated for Best Picture and features one of cinema\'s most emotional opening sequences.' },
        { word: 'COCO', trivia: 'Coco took six years to produce and became the highest-grossing film of all time in Mexico, celebrating Día de Muertos.' },
        { word: 'HAMILTON', trivia: 'Lin-Manuel Miranda wrote the first song for Hamilton during his honeymoon after reading Ron Chernow\'s biography of Alexander Hamilton in 2008.' },
        { word: 'DUNE', trivia: 'Dune has been adapted for screen three times, with Denis Villeneuve\'s version using massive practical sets in the Jordanian desert.' },
        { word: 'TENET', trivia: 'Tenet features no green screen shots and actually crashed a real Boeing 747 airplane into a building for maximum authenticity.' },
        { word: 'LOGAN', trivia: 'Logan was the first superhero movie nominated for Best Adapted Screenplay, treating the comic book genre with dramatic gravitas.' },
        { word: 'WHIPLASH', trivia: 'Whiplash was shot in just nineteen days with a budget under four million dollars, yet earned five Oscar nominations.' },
        { word: 'ALIEN', trivia: 'The slime used for the Alien xenomorph was K-Y Jelly, and the iconic chestburster scene shocked the cast during filming.' },
        { word: 'ROCKY', trivia: 'Sylvester Stallone wrote the script for Rocky in three and a half days and refused to sell it unless he starred.' },
        { word: 'JAWS', trivia: 'The mechanical shark in Jaws malfunctioned so often that Spielberg nicknamed it Bruce and creatively worked around its failures.' },
        { word: 'PULP FICTION', trivia: 'Pulp Fiction cost only $8.5 million to make but revolutionized independent cinema with its non-linear narrative structure and sharp dialogue.' },
        { word: 'FORREST GUMP', trivia: 'Tom Hanks was not paid upfront for Forrest Gump but took percentage points instead, ultimately earning over sixty million dollars.' },
        { word: 'FIGHT CLUB', trivia: 'Brad Pitt and Edward Norton really learned soap-making for Fight Club and Pitt chipped his tooth for authentic realism.' },
        { word: 'GOODFELLAS', trivia: 'The famous "Funny how?" scene in Goodfellas was improvised by Joe Pesci based on a real-life incident from his youth.' },
        { word: 'SPIRITED AWAY', trivia: 'Spirited Away is the highest-grossing film in Japanese history and won the Academy Award for Best Animated Feature in 2003.' },
        { word: 'THE LION KING', trivia: 'The Lion King was originally titled "King of the Jungle" until creators realized lions don\'t actually live in jungles but savannas.' },
        { word: 'WALL-E', trivia: 'WALL-E was named after Walter Elias Disney and features only thirty-nine minutes of dialogue in its nearly two-hour runtime.' },
        { word: 'TOY STORY', trivia: 'Toy Story was the first feature-length computer-animated film ever made, revolutionizing animation and launching Pixar\'s legendary success story.' },
        { word: 'CASABLANCA', trivia: 'Nobody knew how Casablanca would end until the last days of shooting, including lead actors Humphrey Bogart and Ingrid Bergman.' },
        { word: 'PSYCHO', trivia: 'Psycho was the first American film to show a toilet flushing and revolutionized horror by killing its protagonist halfway through.' },
        { word: 'VERTIGO', trivia: 'Vertigo introduced the revolutionary "dolly zoom" camera effect, combining forward zoom with backward tracking to create disorienting perspective shifts.' },
        { word: 'CITIZEN KANE', trivia: 'Citizen Kane is often cited as the greatest film ever made for its innovative cinematography, narrative structure, and deep-focus photography.' },
        { word: 'SHAWSHANK', trivia: 'The Shawshank Redemption was a box office disappointment upon release but became beloved through cable TV and home video.' },
        { word: 'SCHINDLER', trivia: 'Steven Spielberg refused to accept any salary for Schindler\'s List, considering it blood money from depicting the Holocaust tragedy.' },
        { word: 'APOCALYPSE NOW', trivia: 'Apocalypse Now took over three years to edit and Martin Sheen suffered a near-fatal heart attack during the grueling shoot.' },
        { word: 'BLADE RUNNER', trivia: 'Blade Runner is based on Philip K. Dick\'s novel "Do Androids Dream of Electric Sheep?" and has seven different official cuts.' },
        { word: 'MEMENTO', trivia: 'Memento tells its story in two sequences—one in color moving backwards, one in black and white moving forwards—meeting at the end.' },
        { word: 'PRESTIGE', trivia: 'The Prestige features David Bowie as Nikola Tesla and explores the dangerous obsession between two rival magicians in Victorian London.' },
        { word: 'DEPARTED', trivia: 'The Departed is a remake of Hong Kong\'s "Infernal Affairs" and won Martin Scorsese his first and only Best Director Oscar.' },
        { word: 'DARK KNIGHT', trivia: 'The Dark Knight was the first superhero movie to gross over $1 billion and Heath Ledger posthumously won an Oscar.' },
        { word: 'BATMAN', trivia: 'Batman was created by Bob Kane and Bill Finger in 1939, becoming one of the most iconic and enduring superheroes.' },
        { word: 'SUPERMAN', trivia: 'Superman was the first superhero to get a major feature film in 1978, launching the modern superhero movie genre entirely.' },
        { word: 'SPIDERMAN', trivia: 'Spider-Man was almost directed as a horror movie by Tobe Hooper in the 1980s before Sam Raimi\'s iconic 2002 adaptation.' },
        { word: 'AVENGERS', trivia: 'The Avengers was the first Marvel movie to gross over $1 billion, culminating five years of interconnected Marvel Cinematic Universe.' },
        { word: 'IRONMAN', trivia: 'Robert Downey Jr. improvised the iconic line "I am Iron Man" at the end, fundamentally changing Marvel\'s secretive superhero approach.' },
        { word: 'THOR', trivia: 'Tom Hiddleston originally auditioned for the role of Thor before being cast as the far more compelling villain Loki instead.' },
        { word: 'HULK', trivia: 'The Hulk was originally supposed to be grey in the comics, but printing inconsistencies led Stan Lee to change him green.' },
        { word: 'WONDER WOMAN', trivia: 'Wonder Woman was created by psychologist William Moulton Marston, who also invented the polygraph lie detector test in the 1920s.' },
        { word: 'AQUAMAN', trivia: 'Aquaman is the highest-grossing DC Extended Universe film of all time, earning over $1.1 billion worldwide surprisingly successfully.' },
        { word: 'BLACK PANTHER', trivia: 'Black Panther was the first superhero movie nominated for Best Picture and won three Academy Awards including Best Original Score.' },
        { word: 'CAPTAIN MARVEL', trivia: 'Captain Marvel was the first female-led Marvel Cinematic Universe movie and grossed over $1 billion worldwide in its theatrical run.' },
        { word: 'GUARDIANS', trivia: 'Vin Diesel recorded "I am Groot" over one thousand times in multiple languages for the Guardians of the Galaxy franchise.' },
        { word: 'DEADPOOL', trivia: 'Deadpool was the highest-grossing R-rated movie of all time until Joker surpassed it, revolutionizing adult superhero filmmaking completely.' },
        { word: 'WOLVERINE', trivia: 'Hugh Jackman played Wolverine for seventeen years across nine films, making it one of the longest character portrayals in cinema.' },
        { word: 'JURASSIC PARK', trivia: 'The T-Rex roar in Jurassic Park was created by mixing sounds from a baby elephant, tiger, and alligator together.' },
        { word: 'STAR WARS', trivia: 'Yoda was almost played by a monkey wearing a mask before Frank Oz created the iconic puppet performance we know.' },
        { word: 'BACK TO THE FUTURE', trivia: 'The time machine in Back to the Future was originally going to be a refrigerator before the DeLorean car was chosen.' },
        { word: 'INDIANA JONES', trivia: 'Indiana Jones was named after George Lucas\'s Alaskan Malamute dog that also inspired the character of Chewbacca in Star Wars.' },
        { word: 'TERMINATOR', trivia: 'O.J. Simpson was seriously considered for the role of the Terminator but James Cameron thought he was too nice for it.' },
        { word: 'GHOSTBUSTERS', trivia: 'The phone number shown in Ghostbusters was a real working number that received thousands of calls from fans wanting ghostbusting services.' },
        { word: 'ET', trivia: 'E.T.\'s face was modeled after the faces of Albert Einstein, Carl Sandburg, and a pug dog to create his endearing appearance.' },
        { word: 'HOME ALONE', trivia: 'The photo of Buzz\'s girlfriend in Home Alone was actually the art director\'s son in a wig to avoid insulting anyone.' },
        { word: 'SHREK', trivia: 'Shrek was originally voiced by Chris Farley who recorded most of the dialogue before his tragic death, then recast with Mike Myers.' },
        { word: 'FINDING NEMO', trivia: 'Finding Nemo is the best-selling DVD of all time and required Pixar to develop new animation technology for underwater scenes.' },
        { word: 'JOJO RABBIT', trivia: 'Jojo Rabbit features Taika Waititi as an imaginary Adolf Hitler, using satire to critique fascism through a child\'s innocent eyes.' },
        { word: 'MOONLIGHT', trivia: 'Moonlight won Best Picture in the most dramatic Oscar moment ever after La La Land was mistakenly announced as winner.' },
        { word: 'ARRIVAL', trivia: 'Arrival\'s circular alien language was designed by production to be functionally readable, based on real linguistic principles of communication meanings.' },
        { word: 'HEREDITARY', trivia: 'Hereditary features Toni Collette\'s terrifying performance that many considered Oscar-worthy, though horror films rarely receive Academy Award recognition traditionally.' },
        { word: 'KNIVES OUT', trivia: 'Knives Out was written specifically for Daniel Craig to play against type from James Bond, creating a charming Southern detective character.' },
        { word: 'NOMADLAND', trivia: 'Nomadland cast real nomads alongside Frances McDormand, who actually lived in a van for months learning the authentic nomadic lifestyle.' },
        { word: 'SOUL', trivia: 'Soul was Pixar\'s first film with a Black protagonist and explores existential themes rarely tackled in mainstream animated family features.' },
        { word: 'DUNE', trivia: 'Dune\'s sandworms required entirely new digital effects technology and the film\'s sound design won the Academy Award for excellence.' },
        { word: 'WEST SIDE STORY', trivia: 'Steven Spielberg\'s West Side Story remake cast actual Puerto Rican and Latino actors, correcting the problematic casting of the original.' },
        {
            word: 'POWER OF DOG', trivia: 'The Power of the Dog showcases Benedict Cumberbatch's transformative performance, learning real ranch skills for his menacing cowboy character authentically.' },
        { word: 'LICORICE PIZZA', trivia: 'Licorice Pizza is named after a Southern California record store chain and captures the nostalgic atmosphere of 1970s San Fernando.' },
        { word: 'BELFAST', trivia: 'Belfast is Kenneth Branagh\'s semi-autobiographical film about his childhood during the Northern Ireland Troubles in the late nineteen-sixties, shot beautifully.' },
        { word: 'KING RICHARD', trivia: 'Will Smith won his first Oscar for playing Richard Williams, the determined father who coached Venus and Serena Williams relentlessly.' },
        { word: 'ENCANTO', trivia: 'Encanto became a cultural phenomenon with "We Don\'t Talk About Bruno" becoming Disney\'s biggest hit song in decades surprisingly quickly.' },
        { word: 'CRUELLA', trivia: 'Cruella reimagines the villain origin story with stunning punk rock fashion and Emma Stone\'s captivating dual-personality performance throughout the film.' },
        { word: 'DUNE', trivia: 'Dune used minimal CGI for desert scenes, filming in Jordan\'s Wadi Rum with massive practical sets for maximum visual authenticity.' },
        { word: 'NO TIME TO DIE', trivia: 'No Time to Die marked Daniel Craig\'s final performance as James Bond after fifteen years, ending with a shocking and unprecedented finale.' },
        { word: 'SPIDER-MAN', trivia: 'Spider-Man No Way Home brought together three generations of Spider-Men, becoming the highest-grossing film of the pandemic era spectacularly.' },
        { word: 'BATMAN', trivia: 'The Batman reimagines the Dark Knight as a noir detective thriller with Robert Pattinson\'s brooding and vengeful younger Bruce Wayne.' },
        { word: 'UNCHARTED', trivia: 'Uncharted adapts the beloved PlayStation video game series with Tom Holland and Mark Wahlberg treasure hunting across exotic global locations.' },
        { word: 'TOP GUN', trivia: 'Top Gun Maverick became Tom Cruise\'s highest-grossing film ever, released thirty-six years after the original Top Gun in 1986.' },
        { word: 'ELVIS', trivia: 'Elvis features Austin Butler\'s transformative performance, singing all the early Elvis songs himself after two years of intensive vocal preparation.' },
        { word: 'NOPE', trivia: 'Nope is Jordan Peele\'s sci-fi horror exploring spectacle and exploitation through a mysterious UFO terrorizing a California horse ranch.' },
        { word: 'EVERYTHING EVERYWHERE', trivia: 'Everything Everywhere All at Once swept the Oscars with seven wins, featuring Michelle Yeoh as the first Asian Best Actress.' },
        { word: 'TAR', trivia: 'Tár showcases Cate Blanchett\'s masterful performance as a fictional conductor, learning to actually conduct orchestras for authentic classical music scenes.' },
        { word: 'TRIANGLE OF SADNESS', trivia: 'Triangle of Sadness satirizes wealth inequality through a luxury yacht disaster, winning the Palme d\'Or at Cannes Film Festival deservedly.' },
        { word: 'AFTERSUN', trivia: 'Aftersun is a poignant debut exploring memory and depression through a father-daughter Turkish vacation filmed with intimate emotional vulnerability throughout.' },
        { word: 'WOMEN TALKING', trivia: 'Women Talking examines a Mennonite community grappling with sexual assault, featuring powerful ensemble performances discussing justice and faith courageously.' },
        { word: 'GLASS ONION', trivia: 'Glass Onion continues Benoit Blanc mysteries with an all-star cast trapped on a tech billionaire\'s private Greek island during pandemic.' },
        { word: 'BABYLON', trivia: 'Babylon depicts 1920s Hollywood\'s transition from silent films to talkies with Damien Chazelle\'s characteristically energetic and excessive filmmaking style.' },
        { word: 'AVATAR 2', trivia: 'Avatar The Way of Water took over a decade to make, using groundbreaking underwater motion-capture technology never attempted before.' },
        { word: 'PUSS IN BOOTS', trivia: 'Puss in Boots The Last Wish explores mortality and anxiety with surprising emotional depth for a Shrek spinoff animated sequel.' },
        { word: 'TURNING RED', trivia: 'Turning Red is Pixar\'s first film solely directed by a woman, Domee Shi, celebrating Chinese-Canadian culture and adolescent transformation beautifully.' },
        { word: 'COCAINE BEAR', trivia: 'Cocaine Bear is based on the true story of a black bear that consumed seventy pounds of cocaine in 1985.' },
        { word: 'SCREAM 6', trivia: 'Scream VI moves the franchise to New York City, becoming the highest-grossing Scream film in the entire horror franchise successfully.' },
        { word: 'CREED 3', trivia: 'Creed III marks Michael B. Jordan\'s directorial debut while continuing the Rocky legacy with powerful boxing drama and emotional family stakes.' },
        { word: 'DUNGEONS DRAGONS', trivia: 'Dungeons and Dragons Honor Among Thieves perfectly captures tabletop gaming spirit with humor, heart, and surprisingly faithful fantasy adventure storytelling throughout.' },
        { word: 'JOHN WICK 4', trivia: 'John Wick Chapter Four features increasingly elaborate action sequences including a breathtaking continuous staircase fight lasting several uncut minutes spectacularly.' },
        { word: 'GUARDIANS 3', trivia: 'Guardians of the Galaxy Vol Three provides an emotional conclusion to James Gunn\'s trilogy with Rocket Raccoon\'s heartbreaking origin story.' },
        { word: 'FAST X', trivia: 'Fast X is the tenth main Fast and Furious film, continuing the franchise\'s tradition of impossible stunts and family themes.' },
        { word: 'SPIDER-MAN', trivia: 'Spider-Man Across the Spider-Verse features revolutionary animation with six different art styles representing various parallel Spider-verse dimensions beautifully rendered throughout.' },
        { word: 'TRANSFORMERS', trivia: 'Transformers Rise of the Beasts introduces the Maximals to live-action, set in 1990s Brooklyn with nostalgic hip-hop soundtrack vibes.' },
        { word: 'INDIANA JONES 5', trivia: 'Indiana Jones and the Dial of Destiny marks Harrison Ford\'s final adventure as the iconic archaeologist after forty-two years playing character.' },
        { word: 'MISSION IMPOSSIBLE', trivia: 'Mission Impossible Dead Reckoning features Tom Cruise riding a motorcycle off a Norwegian cliff, the most dangerous stunt ever filmed.' },
        { word: 'OPPENHEIMER', trivia: 'Oppenheimer was shot entirely on IMAX film cameras with no CGI for the nuclear explosion, creating practical effects spectacularly realistic.' },
        { word: 'BARBIE', trivia: 'Barbie became the highest-grossing film of 2023, using vibrant pink aesthetics to deliver surprisingly sharp feminist social commentary throughout beautifully.' },
        { word: 'SOUND OF FREEDOM', trivia: 'Sound of Freedom became a surprising box office success, raising awareness about human trafficking through Jim Caviezel\'s passionate performance earnestly.' },
        { word: 'TALK TO ME', trivia: 'Talk to Me is an Australian horror about a supernatural hand that lets teenagers talk to the dead with terrifying addictive consequences.' },
        { word: 'GRAN TURISMO', trivia: 'Gran Turismo tells the true story of a gamer who became a professional race car driver through PlayStation\'s driving simulator.' },
        { word: 'BLUE BEETLE', trivia: 'Blue Beetle is DC\'s first Latino superhero film, celebrating Mexican-American culture while introducing the alien scarab suit technology wonderfully.' },
        { word: 'EQUALIZER 3', trivia: 'The Equalizer 3 sees Denzel Washington\'s Robert McCall retiring to Italy, delivering justice one last time in picturesque Mediterranean settings.' },
        { word: 'EXPENDABLES 4', trivia: 'Expend4bles continues the aging action star ensemble franchise with Jason Statham taking a larger role from Sylvester Stallone this time.' },
        { word: 'NUN 2', trivia: 'The Nun II continues the Conjuring Universe demon Valak storyline with more Catholic horror atmosphere in 1950s French boarding school.' },
        { word: 'CREATOR', trivia: 'The Creator explores AI consciousness through stunning science fiction visuals shot on location in Thailand for authentic futuristic atmosphere beautifully.' },
        { word: 'EXORCIST', trivia: 'The Exorcist Believer brings back Ellen Burstyn from the 1973 original for a new generation of demonic possession horror.' },
        { word: 'PAW PATROL', trivia: 'PAW Patrol The Mighty Movie brings superpowers to the beloved children\'s rescue dogs in their second theatrical animated adventure film.' },
        { word: 'KILLERS FLOWER', trivia: 'Killers of the Flower Moon reunites Scorsese with De Niro and DiCaprio for a three-and-a-half-hour epic about Osage murders.' },
        { word: 'FIVE NIGHTS', trivia: 'Five Nights at Freddy\'s adapts the horror video game phenomenon with animatronic terror, becoming Blumhouse\'s highest-grossing film ever.' },
        { word: 'TAYLOR SWIFT', trivia: 'Taylor Swift The Eras Tour became the highest-grossing concert film ever, bypassing traditional studios to distribute directly through AMC.' },
        { word: 'NAPOLEON', trivia: 'Napoleon features Ridley Scott directing Joaquin Phoenix as the French emperor in a sweeping historical epic spanning decades of conquest.' },
        { word: 'WISH', trivia: 'Wish celebrates Disney\'s 100th anniversary with a musical fairy tale combining traditional hand-drawn animation with modern CGI techniques beautifully.' },
        { word: 'HUNGER GAMES', trivia: 'The Hunger Games Ballad of Songbirds and Snakes explores President Snow\'s origin story sixty-four years before Katniss Everdeen\'s rebellion begins.' },
        { word: 'RENAISSANCE', trivia: 'Renaissance A Film by Beyoncé documents her record-breaking world tour with stunning concert footage and intimate behind-the-scenes creative process.' },
        { word: 'WONKA', trivia: 'Wonka stars Timothée Chalamet as young Willy Wonka in a musical origin story exploring how he became the famous chocolatier.' },
        { word: 'AQUAMAN 2', trivia: 'Aquaman and the Lost Kingdom concludes Jason Momoa\'s underwater superhero journey while navigating behind-the-scenes production controversies throughout difficult filming.' },
        { word: 'MIGRATION', trivia: 'Migration is Illumination\'s animated comedy about a family of ducks taking their first migration journey from New England to Jamaica.' },
        { word: 'ANYONE BUT YOU', trivia: 'Anyone But You revives the romantic comedy genre with Sydney Sweeney and Glen Powell\'s chemistry in an Australian destination wedding setting.' },
        { word: 'MEAN GIRLS', trivia: 'Mean Girls musical film adapts the Broadway show based on the 2004 cult classic, bringing fetch back for Gen Z.' },
        { word: 'AMERICAN FICTION', trivia: 'American Fiction satirizes the publishing industry\'s expectations of Black authors through Jeffrey Wright\'s frustrated novelist creating a stereotypical bestseller ironically.' },
        { word: 'POOR THINGS', trivia: 'Poor Things features Emma Stone\'s outrageous performance as a reanimated Victorian woman discovering life, winning her second Best Actress Oscar.' },
        { word: 'ZONE OF INTEREST', trivia: 'The Zone of Interest depicts a Nazi commandant\'s family living next to Auschwitz, exploring banality of evil through chilling domestic scenes.' },
        { word: 'FERRARI', trivia: 'Ferrari chronicles Enzo Ferrari\'s 1957 crisis balancing his crumbling marriage with building his legendary racing empire in post-war Italy dramatically.' },
        { word: 'MAESTRO', trivia: 'Maestro showcases Bradley Cooper directing and starring as composer Leonard Bernstein, wearing extensive prosthetic makeup for authentic portrayal spanning decades.' },
        { word: 'NYAD', trivia: 'Nyad tells the true story of Diana Nyad swimming from Cuba to Florida at age sixty-four after four previous attempts.' },
        { word: 'SOCIETY OF SNOW', trivia: 'Society of the Snow depicts the 1972 Andes plane crash survivors who resorted to cannibalism, told from victims\' perspective.' },
        { word: 'RUSTIN', trivia: 'Rustin highlights Bayard Rustin\'s crucial role organizing the 1963 March on Washington despite facing homophobia within the civil rights movement.' },
        { word: 'HOLDOVERS', trivia: 'The Holdovers reunites Alexander Payne with Paul Giamatti for a heartwarming Christmas story set at a New England boarding school.' },
        { word: 'ANATOMY FALL', trivia: 'Anatomy of a Fall won the Palme d\'Or at Cannes, examining a writer\'s trial for her husband\'s death through ambiguous evidence.' },
        { word: 'FALLEN LEAVES', trivia: 'Fallen Leaves is a minimalist Finnish romance about lonely working-class people finding love in modern Helsinki\'s economic precarity beautifully.' },
        { word: 'PAST LIVES', trivia: 'Past Lives explores childhood sweethearts reuniting decades later, questioning what might have been in this devastating romantic debut film.' },
        { word: 'MAY DECEMBER', trivia: 'May December stars Natalie Portman studying Julianne Moore\'s character for a film role about a teacher who seduced her student.' },
        { word: 'MONSTER', trivia: 'Monster tells the same bullying incident from three different perspectives, revealing how perception shapes truth in contemporary Japanese society.' },
        { word: 'ALL OF US', trivia: 'All of Us Strangers features Andrew Scott encountering his dead parents as ghosts in his childhood home, exploring grief beautifully.' },
        { word: 'IDEAL HUSBAND', trivia: 'An Ideal Husband adapts Oscar Wilde\'s comedy of political blackmail and Victorian marriage with sharp wit and elaborate period costumes.' },
        { word: 'COLOR PURPLE', trivia: 'The Color Purple musical film adapts Alice Walker\'s novel for a new generation with powerful singing performances from Fantasia Barrino.' },
        { word: 'IRON CLAW', trivia: 'The Iron Claw tells the tragic true story of the Von Erich wrestling family dynasty plagued by death and curse.' },
        { word: 'BOY AND HERON', trivia: 'The Boy and the Heron is Hayao Miyazaki\'s semi-autobiographical fantasy, possibly his final film after multiple retirement announcements previously.' },
        { word: 'GODZILLA MINUS ONE', trivia: 'Godzilla Minus One won the Oscar for Best Visual Effects despite a tiny budget, creating stunning monster action with only thirty-five artists.' },
        { word: 'IMAGINARY', trivia: 'Imaginary is Blumhouse\'s horror about a sinister teddy bear turning childhood imagination into nightmares for a blended family eerily.' },
        { word: 'DUNE PART TWO', trivia: 'Dune Part Two completes Denis Villeneuve\'s adaptation with Paul Atreides\' transformation into the messianic Muad\'Dib among the Fremen people.' },
        { word: 'MADAME WEB', trivia: 'Madame Web explores Spider-Man universe precognition powers with Dakota Johnson as a paramedic who can see the future mysteriously appearing.' },
        { word: 'CABRINI', trivia: 'Cabrini tells the inspiring true story of Italian immigrant Mother Frances Cabrini building a charitable empire in 1890s New York.' },
        { word: 'IMAGINARY FRIENDS', trivia: 'IF features Ryan Reynolds helping kids reconnect with forgotten imaginary friends in John Krasinski\'s heartwarming family fantasy film.' },
        { word: 'CIVIL WAR', trivia: 'Civil War depicts journalists covering a near-future American civil war, exploring media ethics during societal collapse with intense action sequences.' },
        { word: 'ABIGAIL', trivia: 'Abigail is a horror-comedy about kidnappers discovering their victim is a centuries-old ballerina vampire in an isolated mansion wickedly.' },
        { word: 'CHALLENGERS', trivia: 'Challengers explores a competitive love triangle among tennis players with steamy chemistry and Luca Guadagnino\'s stylish direction throughout beautifully shot.' },
        { word: 'FALL GUY', trivia: 'The Fall Guy stars Ryan Gosling as a stuntman solving a conspiracy while rekindling romance with his director ex-girlfriend excitingly.' },
        { word: 'KINGDOM PLANET APES', trivia: 'Kingdom of the Planet of the Apes continues the rebooted franchise generations after Caesar, exploring evolving ape civilization magnificently.' },
        { word: 'FURIOSA', trivia: 'Furiosa chronicles the origin story of Imperator Furiosa before Mad Max Fury Road with Anya Taylor-Joy replacing Charlize Theron.' },
        { word: 'GARFIELD', trivia: 'The Garfield Movie brings the lasagna-loving cat back to theaters with Chris Pratt voicing the famously lazy Monday-hating feline.' },
        { word: 'IF', trivia: 'IF imagines what happens to imaginary friends when children outgrow them, created by and starring John Krasinski with star-studded voices.' },
        { word: 'BAD BOYS 4', trivia: 'Bad Boys Ride or Die reunites Will Smith and Martin Lawrence for another explosive Miami action-comedy adventure thirty years later.' },
        { word: 'INSIDE OUT 2', trivia: 'Inside Out 2 introduces new emotions like Anxiety and Embarrassment as Riley navigates the turbulent waters of teenage years emotionally.' },
        { word: 'QUIET PLACE', trivia: 'A Quiet Place Day One explores the initial alien invasion in New York City before the Abbott family\'s rural survival.' },
        { word: 'KINDS OF KINDNESS', trivia: 'Kinds of Kindness is Yorgos Lanthimos\' anthology film featuring Emma Stone in three bizarre darkly comedic stories about control.' },
        { word: 'BEVERLY HILLS COP 4', trivia: 'Beverly Hills Cop Axel F brings Eddie Murphy back as detective Axel Foley after thirty years for Netflix nostalgia.' },
        { word: 'DESPICABLE ME 4', trivia: 'Despicable Me 4 continues Gru\'s family adventures with the Minions, introducing his nemesis Maxime Le Mal seeking revenge spectacularly.' },
        { word: 'LONGLEGS', trivia: 'Longlegs features Nicolas Cage as a disturbing occult serial killer in this psychological horror thriller directed by Osgood Perkins.' },
        { word: 'TWISTERS', trivia: 'Twisters is a standalone sequel to the 1996 disaster film about storm chasers, updated for modern meteorology and effects.' },
        { word: 'DEADPOOL 3', trivia: 'Deadpool and Wolverine unites Ryan Reynolds with Hugh Jackman\'s Wolverine for the first R-rated Marvel Cinematic Universe film.' },
        { word: 'TRAP', trivia: 'Trap is M. Night Shyamalan\'s thriller about a father attending a pop concert with his daughter while evading police manhunt.' },
        { word: 'BORDERLANDS', trivia: 'Borderlands adapts the chaotic video game with Cate Blanchett leading treasure hunters on the dangerous planet Pandora for riches.' },
        { word: 'ALIEN ROMULUS', trivia: 'Alien Romulus returns the franchise to horror roots with young colonists facing xenomorphs on a derelict space station terrifyingly.' },
        { word: 'IT ENDS WITH US', trivia: 'It Ends with Us adapts Colleen Hoover\'s bestselling romance novel about breaking cycles of domestic abuse courageously and powerfully.' },
        { word: 'CROW', trivia: 'The Crow reboot reimagines the 1994 cult classic about a murdered musician resurrected to avenge his death dramatically.' },
        { word: 'BEETLEJUICE 2', trivia: 'Beetlejuice Beetlejuice reunites Michael Keaton, Winona Ryder, and Tim Burton thirty-six years after the original supernatural comedy film.' },
        { word: 'REAGAN', trivia: 'Reagan biopic stars Dennis Quaid as the 40th president, chronicling his journey from actor to conservative political icon.' },
        { word: 'SPEAK NO EVIL', trivia: 'Speak No Evil is a psychological horror remake about a family\'s increasingly disturbing weekend with new friends at countryside estate.' },
        { word: 'TRANSFORMERS ONE', trivia: 'Transformers One is an animated origin story exploring the friendship between Optimus Prime and Megatron on planet Cybertron beautifully.' },
        { word: 'WILD ROBOT', trivia: 'The Wild Robot follows a shipwrecked robot learning to survive on an uninhabited island by befriending the wildlife inhabitants.' },
        { word: 'CROW', trivia: 'The Crow features Brandon Lee\'s final tragic performance before his accidental death during filming became Hollywood\'s darkest legend.' },
        { word: 'NIGHTMARE CHRISTMAS', trivia: 'The Nightmare Before Christmas was stop-motion animated with 227 puppets, taking three years to complete every frame meticulously.' },
        { word: 'CORALINE', trivia: 'Coraline used 28 identical puppets for the title character, with 207 unique faces created for stop-motion expressions throughout.' },
        { word: 'FANTASTIC MR FOX', trivia: 'Fantastic Mr. Fox used real animal fur on puppets and shot on-location miniature sets for authentic texture and lighting.' },
        { word: 'KUBO', trivia: 'Kubo and the Two Strings features the largest stop-motion puppet ever created—a 16-foot-tall skeleton samurai warrior.' },
        { word: 'MISSING LINK', trivia: 'Missing Link won the Golden Globe for Best Animated Feature despite being Laika\'s biggest box office disappointment sadly.' },
        { word: 'CORPSE BRIDE', trivia: 'Corpse Bride reunited Tim Burton with composer Danny Elfman for a gothic stop-motion musical romance set in Victorian times.' },
        { word: 'BOX TROLLS', trivia: 'The Boxtrolls required 62 animators working simultaneously to complete, with each animator producing approximately 3.31 seconds weekly.' },
        { word: 'PARANORMAN', trivia: 'ParaNorman was the first stop-motion film using color 3D printing for replacement faces, revolutionizing animation facial expressions completely.' },
        { word: 'CHICKEN RUN', trivia: 'Chicken Run was Aardman\'s first feature film, requiring five years of production and becoming the highest-grossing stop-motion movie.' },
        { word: 'WALLACE GROMIT', trivia: 'Wallace and Gromit features no dialogue from Gromit, yet his expressions communicate perfectly through masterful stop-motion animation craft.' },
        { word: 'SHAUN SHEEP', trivia: 'Shaun the Sheep Movie contains no intelligible dialogue, telling its story entirely through visual comedy and animal sounds hilariously.' },
        { word: 'PIRATES', trivia: 'The Pirates! Band of Misfits took over two years to animate with handmade clay sets and intricate water effects.' },
        { word: 'EARLY MAN', trivia: 'Early Man features cavemen versus Bronze Age warriors in a soccer match, combining Aardman\'s humor with stop-motion brilliance.' },
        { word: 'LEGO MOVIE', trivia: 'The LEGO Movie animates CGI to look like stop-motion bricks, with incredible detail making everything appear genuinely handcrafted.' },
        { word: 'LEGO BATMAN', trivia: 'The LEGO Batman Movie references every Batman film and TV show ever made, creating the ultimate Batman parody celebration.' },
        { word: 'LEGO MOVIE 2', trivia: 'The LEGO Movie 2 introduces live-action elements, revealing the entire LEGO universe exists in a real basement playroom.' },
        { word: 'MITCHELLS', trivia: 'The Mitchells vs. the Machines features unique animation style combining 2D and 3D with hand-drawn elements throughout creatively.' },
        { word: 'SPIDER-VERSE', trivia: 'Into the Spider-Verse uses "animating on twos" technique, reducing frame rate to create comic book visual aesthetic innovatively.' },
        { word: 'KLAUS', trivia: 'Klaus revolutionized 2D animation by combining hand-drawn art with 3D lighting, creating a storybook aesthetic beautifully rendered.' },
        { word: 'WOLFWALKERS', trivia: 'Wolfwalkers is Cartoon Saloon\'s Irish folklore trilogy conclusion, featuring stunning hand-drawn animation inspired by medieval illuminated manuscripts beautifully.' },
        { word: 'SONG OF SEA', trivia: 'Song of the Sea draws from Irish mythology about selkies, using watercolor-inspired animation to create dreamlike visual storytelling.' },
        { word: 'SECRET OF KELLS', trivia: 'The Secret of Kells depicts the creation of the Book of Kells with animation inspired by Celtic art patterns.' },
        { word: 'ERNEST CELESTINE', trivia: 'Ernest and Celestine uses watercolor backgrounds with characters drawn on top, creating a storybook illustration aesthetic throughout beautifully.' },
        { word: 'MY LIFE ZUCCHINI', trivia: 'My Life as a Zucchini tackles foster care through stop-motion with surprising emotional depth despite its whimsical character design.' },
        { word: 'LOVING VINCENT', trivia: 'Loving Vincent animates Vincent van Gogh\'s life using 65,000 oil paintings hand-painted in his distinctive style by artists.' },
        { word: 'RED TURTLE', trivia: 'The Red Turtle is a dialogue-free Studio Ghibli co-production about a man shipwrecked on a mysterious island beautifully animated.' },
        { word: 'WHEN MARNIE', trivia: 'When Marnie Was There is Studio Ghibli\'s final hand-drawn film before transitioning to computer-assisted animation unfortunately recently.' },
        { word: 'TALE PRINCESS', trivia: 'The Tale of the Princess Kaguya uses sketchy watercolor animation resembling moving Japanese scroll paintings aesthetically throughout stunningly.' },
        { word: 'WIND RISES', trivia: 'The Wind Rises depicts aircraft designer Jiro Horikoshi, marking Hayao Miyazaki\'s first retirement before returning several years later.' },
        { word: 'PONYO', trivia: 'Ponyo required 170,000 hand-drawn frames without digital animation shortcuts, showcasing Ghibli\'s commitment to traditional craftsmanship beautifully displayed.' },
        { word: 'HOWL CASTLE', trivia: 'Howl\'s Moving Castle adapts Diana Wynne Jones\' novel with stunning steampunk aesthetics and themes about aging and war.' },
        { word: 'GRAVE FIREFLIES', trivia: 'Grave of the Fireflies depicts sibling starvation during WWII, considered one of cinema\'s most devastating anti-war films ever.' },
        { word: 'MY NEIGHBOR TOTORO', trivia: 'My Neighbor Totoro originally flopped in Japan but became beloved worldwide, now serving as Studio Ghibli\'s iconic mascot character.' },
        { word: 'PRINCESS MONONOKE', trivia: 'Princess Mononoke was the highest-grossing Japanese film until Titanic, exploring environmental themes through epic fantasy adventure storytelling.' },
        { word: 'NAUSICAA', trivia: 'Nausicaä of the Valley of the Wind predates Studio Ghibli but inspired its founding, featuring environmentalism and pacifism themes.' },
        { word: 'WHISPER HEART', trivia: 'Whisper of the Heart is a rare realistic Ghibli film about a teenage writer, directed by Yoshifumi Kondō who died young.' },
        { word: 'PORCO ROSSO', trivia: 'Porco Rosso features a pilot cursed to look like a pig, set in interwar Italy with stunning aerial dogfight sequences.' },
        { word: 'OCEAN WAVES', trivia: 'Ocean Waves was Ghibli\'s only television film, created by younger staff to experiment with realistic high school romance.' },
        { word: 'POM POKO', trivia: 'Pom Poko features shapeshifting tanuki raccoon dogs protesting suburban development through environmental activism comedically portrayed throughout humorously.' },
        { word: 'CASTLE IN SKY', trivia: 'Castle in the Sky features steampunk floating islands and was Ghibli\'s first official film establishing the studio\'s signature style.' },
        { word: 'KIKI DELIVERY', trivia: 'Kiki\'s Delivery Service explores teenage independence through a young witch starting a delivery business in a European-inspired seaside town.' },
        { word: 'ONLY YESTERDAY', trivia: 'Only Yesterday contemplates adult life choices through childhood flashbacks, depicting ordinary Japanese life with unusual realism for animation.' },
        { word: 'ARIETTY', trivia: 'Arrietty adapts The Borrowers with miniature people living secretly under floorboards, rendered beautifully at tiny scale throughout wonderfully.' },
        { word: 'FROM UP POPPY', trivia: 'From Up on Poppy Hill is set in 1960s Yokohama, exploring teenage romance against modernization debates during Olympic preparations.' },
        { word: 'MARNIE', trivia: 'When Marnie Was There is a psychological mystery about isolation and identity with dreamlike watercolor backgrounds throughout the film.' },
        { word: 'CAT RETURNS', trivia: 'The Cat Returns spins off from Whisper of the Heart with fantastical cat kingdom adventures full of whimsy and humor.' },
        { word: 'EARWIG WITCH', trivia: 'Earwig and the Witch is Ghibli\'s first fully CGI film, departing from hand-drawn tradition to mixed fan reception.' },
        { word: 'THOUSAND', trivia: 'Spirited Away won the Oscar for Best Animated Feature, introducing millions to Studio Ghibli\'s magical storytelling worldwide successfully.' },
        { word: 'AKIRA', trivia: 'Akira pioneered anime\'s global popularity with cyberpunk Neo-Tokyo dystopia, revolutionary animation, and unprecedented production budget for animation.' }
    ],
    'Science': [
        { word: 'GRAVITY', trivia: 'Gravity attracts all objects toward Earth\'s center, with Isaac Newton describing this fundamental force after observing falling apples famously.' },
        { word: 'ATOM', trivia: 'Atoms are mostly empty space with tiny nuclei, yet they combine to form all matter throughout the observable universe.' },
        { word: 'NEURON', trivia: 'The human brain contains approximately 86 billion neurons communicating through electrical and chemical signals, forming complex thoughts and consciousness.' },
        { word: 'GALAXY', trivia: 'The Milky Way galaxy spans about 100,000 light-years across and contains roughly 100 to 400 billion stars orbiting together.' },
        { word: 'PHYSICS', trivia: 'Physics is the natural science studying matter, energy, space, and time to understand how the universe fundamentally operates.' },
        { word: 'QUANTUM', trivia: 'Quantum mechanics describes matter behavior at atomic scales, where particles exist in multiple states simultaneously until observed strangely.' },
        { word: 'ORBIT', trivia: 'The Moon orbits Earth every 27.3 days, causing tides through gravitational pull while gradually drifting away yearly.' },
        { word: 'FOSSIL', trivia: 'Fossils preserve ancient organisms in rock, providing crucial evidence about evolution and Earth\'s biological history over millions of years.' },
        { word: 'VIRUS', trivia: 'Viruses aren\'t considered living organisms by many biologists since they require host cells to reproduce and lack independent metabolism.' },
        { word: 'ROBOT', trivia: 'The word "robot" comes from Czech "robota" meaning forced labor, first used in Karel Čapek\'s 1920 science fiction play.' },
        { word: 'ENERGY', trivia: 'Energy cannot be created or destroyed according to thermodynamics, only transformed between kinetic, potential, and other forms constantly.' },
        { word: 'LASER', trivia: 'LASER stands for Light Amplification by Stimulated Emission of Radiation, producing coherent focused beams for countless modern applications.' },
        { word: 'PRISM', trivia: 'A prism breaks white light into constituent spectral colors, demonstrating how light consists of different wavelengths traveling together.' },
        { word: 'MAGNET', trivia: 'Magnets have two poles called North and South that attract opposite poles and repel identical ones through invisible magnetic fields.' },
        { word: 'CLONE', trivia: 'Dolly the sheep was the first mammal cloned from an adult somatic cell in 1996, raising ethical questions worldwide.' },
        { word: 'DNA', trivia: 'DNA contains genetic instructions for development of all known living organisms, structured as double helix discovered by Watson and Crick.' },
        { word: 'CELL', trivia: 'The cell is the basic structural and functional unit of life, with humans containing approximately 37 trillion cells working together.' },
        { word: 'ACID', trivia: 'Acids have pH less than seven and taste sour, donating hydrogen ions in chemical reactions throughout nature and industry.' },
        { word: 'BASE', trivia: 'Bases have pH greater than seven and feel slippery, accepting hydrogen ions and neutralizing acids in chemical reactions systematically.' },
        { word: 'WAVE', trivia: 'Sound waves cannot travel through vacuum since they require medium to propagate, unlike light which travels fastest through emptiness.' },
        { word: 'ECLIPSE', trivia: 'A solar eclipse occurs when the Moon passes between Earth and Sun, blocking sunlight and casting shadows across Earth.' },
        { word: 'TELESCOPE', trivia: 'The Hubble Space Telescope was launched in 1990, revolutionizing astronomy by capturing unprecedented deep space images from orbit above.' },
        { word: 'MICROSCOPE', trivia: 'Microscopes allow viewing objects too small for naked eyes, revealing microscopic worlds of cells, bacteria, and molecular structures beautifully.' },
        { word: 'BACTERIA', trivia: 'There are more bacteria in your mouth than people in the world, with trillions living throughout your body beneficially.' },
        { word: 'VACCINE', trivia: 'The first vaccine was developed for smallpox by Edward Jenner in 1796, eventually eradicating the disease globally by 1980.' },
        { word: 'SATELLITE', trivia: 'The Moon is Earth\'s only natural satellite, while thousands of artificial satellites orbit Earth providing communications and GPS services.' },
        { word: 'ASTEROID', trivia: 'Most asteroids orbit the Sun between Mars and Jupiter in the asteroid belt, remnants from solar system formation billions ago.' },
        { word: 'COMET', trivia: 'Comets are cosmic snowballs of frozen gases, rock, and dust orbiting the Sun, developing brilliant tails when approaching closer.' },
        { word: 'MOLECULE', trivia: 'A molecule is a group of atoms bonded together, representing the smallest fundamental unit of a chemical compound structure.' },
        { word: 'ELECTRON', trivia: 'Electrons have negative electric charge and orbit atomic nuclei, participating in chemical bonds and creating electrical current flows.' },
        { word: 'PROTON', trivia: 'Protons have positive electric charge and reside in atomic nuclei, determining each element\'s identity on the periodic table.' },
        { word: 'NEUTRON', trivia: 'Neutrons have no electric charge and stabilize atomic nuclei, with varying numbers creating different isotopes of elements systematically.' },
        { word: 'PHOTON', trivia: 'A photon is a particle of light exhibiting wave-particle duality, traveling at the universe\'s absolute maximum speed limit.' },
        { word: 'PLASMA', trivia: 'Plasma is the fourth state of matter, consisting of ionized gas found in stars, lightning, and fluorescent lights.' },
        { word: 'CRYSTAL', trivia: 'Crystals have highly ordered microscopic structure, forming beautiful geometric patterns as atoms arrange in repeating lattices systematically throughout.' },
        { word: 'ENZYME', trivia: 'Enzymes are biological catalysts speeding chemical reactions without being consumed, essential for all living organisms\' metabolic processes constantly.' },
        { word: 'PROTEIN', trivia: 'Proteins are large biomolecules performing countless functions in organisms, built from amino acids in complex folded three-dimensional structures.' },
        { word: 'CARBON', trivia: 'Carbon is the chemical basis for all known life, forming four bonds enabling complex organic molecules essential for biology.' },
        { word: 'OXYGEN', trivia: 'Oxygen makes up about 21% of Earth\'s atmosphere and is essential for cellular respiration in most living organisms constantly.' },
        { word: 'HYDROGEN', trivia: 'Hydrogen is the most abundant chemical substance in the universe, comprising about 75% of all normal matter observed.' },
        { word: 'NITROGEN', trivia: 'Nitrogen makes up about 78% of Earth\'s atmosphere but must be fixed by bacteria before plants can use it.' },
        { word: 'HELIUM', trivia: 'Helium is the second lightest and second most abundant element, discovered in the Sun\'s spectrum before Earth.' },
        { word: 'SODIUM', trivia: 'Sodium is a soft silvery-white highly reactive metal that explodes violently when exposed to water dramatically in demonstrations.' },
        { word: 'CALCIUM', trivia: 'Calcium is essential for living organisms, particularly in cell physiology, bone formation, and muscle contraction processes throughout bodies.' },
        { word: 'IRON', trivia: 'Iron is the most common element on Earth by mass, forming our planet\'s core and essential for hemoglobin.' },
        { word: 'COPPER', trivia: 'Copper was the first metal used by humans over 10,000 years ago, valued for conductivity and malleability properties.' },
        { word: 'SPECTRUM', trivia: 'The visible spectrum is the portion of electromagnetic spectrum visible to human eyes, ranging from red to violet wavelengths.' },
        { word: 'RADIATION', trivia: 'Radiation is energy transmission through waves or particles, including both harmless radio waves and dangerous gamma radiation types.' },
        { word: 'FRICTION', trivia: 'Friction is the force resisting relative motion of solid surfaces, converting kinetic energy into heat during contact interactions.' },
        { word: 'MOMENTUM', trivia: 'Momentum is the product of mass and velocity, conserved in closed systems according to Newton\'s fundamental physics laws.' },
        { word: 'VELOCITY', trivia: 'Velocity is the speed of an object in a given direction, differing from speed by including directional information.' },
        { word: 'ACCELERATION', trivia: 'Acceleration is the rate of change of velocity over time, measured in meters per second squared in physics.' },
        { word: 'FORCE', trivia: 'Force is any interaction that, when unopposed, will change an object\'s motion according to Newton\'s fundamental laws of physics.' },
        { word: 'PRESSURE', trivia: 'Pressure is force applied perpendicular to a surface per unit area, measured in pascals or pounds per square inch.' },
        { word: 'VOLUME', trivia: 'Volume is three-dimensional space quantity enclosed by a closed surface, measured in cubic meters or liters typically.' },
        { word: 'EVOLUTION', trivia: 'Charles Darwin proposed evolution by natural selection, explaining how species change over generations through inherited trait variations gradually.' },
        { word: 'PHOTOSYNTHESIS', trivia: 'Photosynthesis converts light energy into chemical energy in plants, producing oxygen as byproduct and sustaining most Earth life.' },
        { word: 'ECOSYSTEM', trivia: 'An ecosystem is a community of living organisms interacting with nonliving components of their environment in complex balanced relationships.' },
        { word: 'BIOLOGY', trivia: 'Biology is the natural science studying life and living organisms, their structure, function, growth, evolution, and distribution patterns.' },
        { word: 'CHEMISTRY', trivia: 'Chemistry is the scientific discipline studying elements, compounds, and how matter interacts, transforms, and bonds throughout reactions systematically.' },
        { word: 'ASTRONOMY', trivia: 'Astronomy is the study of celestial objects and phenomena beyond Earth\'s atmosphere, including stars, planets, galaxies, and cosmology.' },
        { word: 'GEOLOGY', trivia: 'Geology is earth science concerned with solid Earth, rocks, processes shaping Earth\'s surface, and 4.5 billion year history.' },
        { word: 'METEOR', trivia: 'A meteor is a meteoroid that has entered Earth\'s atmosphere, creating a bright streak called a shooting star.' },
        { word: 'BLACK HOLE', trivia: 'A black hole is spacetime region where gravity is so strong that nothing, not even light, can escape.' },
        { word: 'SUPERNOVA', trivia: 'A supernova is a powerful stellar explosion occurring when massive stars exhaust fuel, briefly outshining entire galaxies spectacularly.' },
        { word: 'MITOSIS', trivia: 'Mitosis is cell division creating two identical daughter cells, essential for growth and tissue repair in multicellular organisms constantly.' },
        { word: 'DARWIN', trivia: 'Charles Darwin developed evolution theory after observing Galápagos finches, revolutionizing biology with natural selection concept fundamentally.' },
        { word: 'EINSTEIN', trivia: 'Albert Einstein developed relativity theories, showing time and space are relative, and E=mc² connects mass with energy.' },
        { word: 'NEWTON', trivia: 'Isaac Newton formulated three laws of motion and universal gravitation, laying foundations for classical mechanics and physics principles.' },
        { word: 'CURIE', trivia: 'Marie Curie discovered radioactive elements polonium and radium, winning two Nobel Prizes in different scientific fields remarkably.' },
        { word: 'TESLA', trivia: 'Nikola Tesla invented alternating current electrical systems, wireless transmission, and numerous innovations in electromagnetism and energy transfer.' },
        { word: 'HAWKING', trivia: 'Stephen Hawking theorized about black holes emitting radiation and authored "A Brief History of Time," popularizing cosmology globally.' },
        { word: 'MENDEL', trivia: 'Gregor Mendel discovered genetics principles through pea plant experiments, establishing inheritance laws fundamental to modern biology today.' },
        { word: 'GALILEO', trivia: 'Galileo improved the telescope, discovered Jupiter\'s moons, and championed heliocentrism despite Catholic Church opposition to his findings.' },
        { word: 'PASTEUR', trivia: 'Louis Pasteur discovered pasteurization, germ theory, and created vaccines for rabies and anthrax, saving countless lives through science.' },
        { word: 'FARADAY', trivia: 'Michael Faraday discovered electromagnetic induction, enabling electric generators and motors that power modern civilization extensively and continuously.' },
        { word: 'BOHR', trivia: 'Niels Bohr developed atomic model with electron orbits and contributed foundationally to quantum mechanics theory development during twentieth century.' },
        { word: 'RUTHERFORD', trivia: 'Ernest Rutherford discovered the atomic nucleus through gold foil experiments, fundamentally transforming understanding of atomic structure forever.' },
        { word: 'PLANCK', trivia: 'Max Planck originated quantum theory by proposing energy exists in discrete packets called quanta, revolutionizing physics understanding completely.' },
        { word: 'HEISENBERG', trivia: 'Werner Heisenberg formulated uncertainty principle stating you cannot simultaneously know particle\'s position and momentum with absolute precision ever.' },
        { word: 'SCHRODINGER', trivia: 'Erwin Schrödinger developed wave equation for quantum mechanics and proposed the famous thought experiment with a cat paradox.' },
        { word: 'FEYNMAN', trivia: 'Richard Feynman developed quantum electrodynamics, won Nobel Prize, and became famous for brilliant teaching and bongo drum playing.' },
        { word: 'OPPENHEIMER', trivia: 'J. Robert Oppenheimer led the Manhattan Project developing atomic bombs, later quoting Bhagavad Gita: "I am become Death."' },
        { word: 'SAGAN', trivia: 'Carl Sagan popularized science through "Cosmos" television series and advocated for space exploration and extraterrestrial life search passionately.' },
        { word: 'TYSON', trivia: 'Neil deGrasse Tyson directs Hayden Planetarium and hosted "Cosmos" reboot, making astrophysics accessible and entertaining for millions globally.' },
        { word: 'WATSON', trivia: 'James Watson co-discovered DNA\'s double helix structure with Francis Crick, revolutionizing biology and genetics understanding fundamentally forever.' },
        { word: 'CRICK', trivia: 'Francis Crick co-discovered DNA structure and later worked on consciousness, proposing materialist explanations for subjective experience scientifically boldly.' },
        { word: 'FRANKLIN', trivia: 'Rosalind Franklin\'s x-ray crystallography was crucial for DNA discovery, though her contributions were underrecognized until after her death.' },
        { word: 'MENDELEEV', trivia: 'Dmitri Mendeleev created the periodic table, predicting undiscovered elements through patterns in chemical properties remarkably and accurately.' },
        { word: 'HUBBLE', trivia: 'Edwin Hubble discovered universe expansion and galaxies beyond Milky Way, fundamentally changing cosmology understanding about universe scale.' },
        { word: 'KEPLER', trivia: 'Johannes Kepler discovered planetary motion laws, showing orbits are elliptical rather than circular as previously believed by astronomers.' },
        { word: 'COPERNICUS', trivia: 'Nicolaus Copernicus proposed heliocentric model with Earth orbiting Sun, challenging geocentric worldview held for over thousand years firmly.' },
        { word: 'ARCHIMEDES', trivia: 'Archimedes discovered buoyancy principles, invented numerous machines, and allegedly said "Give me a lever long enough, I\'ll move world."' },
        { word: 'PYTHAGORAS', trivia: 'Pythagoras proved the famous theorem about right triangles and founded mystical school believing mathematics governed reality\'s fundamental nature.' },
        { word: 'EUCLID', trivia: 'Euclid wrote "Elements," systematizing geometry and establishing mathematical proof methods used for over two thousand years in education.' },
        { word: 'TURING', trivia: 'Alan Turing pioneered computer science, cracked Nazi Enigma codes, and proposed the famous Turing Test for artificial intelligence.' },
        { word: 'FIBONACCI', trivia: 'Fibonacci introduced Hindu-Arabic numerals to Europe and discovered famous sequence appearing throughout nature in spirals and patterns.' },
        { word: 'NOBEL', trivia: 'Alfred Nobel invented dynamite, felt guilty about weaponization, and established Nobel Prizes honoring achievements benefiting humanity annually.' },
        { word: 'HOOKE', trivia: 'Robert Hooke discovered cells, formulated Hooke\'s Law about elasticity, and engaged in famous disputes with Isaac Newton bitterly.' },
        { word: 'LEEUWENHOEK', trivia: 'Antonie van Leeuwenhoek created powerful microscopes, discovering microorganisms and describing bacteria, sperm cells, and blood flow.' },
        { word: 'LAVOISIER', trivia: 'Antoine Lavoisier discovered oxygen\'s role in combustion and respiration, establishing modern chemistry before being guillotined during French Revolution.' },
        { word: 'DALTON', trivia: 'John Dalton proposed modern atomic theory explaining chemical reactions and discovered color blindness, which he personally experienced himself.' }
    ]
};
