const GAME_DATA = {
    'Films': [
        { word: 'TITANIC', trivia: 'Titanic was the first film to gross over $1 billion worldwide.' },
        { word: 'AVATAR', trivia: 'Avatar is the highest-grossing film of all time.' },
        { word: 'INCEPTION', trivia: 'Christopher Nolan wrote the script for Inception over 10 years.' },
        { word: 'GLADIATOR', trivia: 'Russell Crowe’s wounds in the opening battle scene were real.' },
        { word: 'JOKER', trivia: 'Joaquin Phoenix lost 52 pounds for his role as the Joker.' },
        { word: 'INTERSTELLAR', trivia: 'Interstellar is a 2014 science fiction film directed by Christopher Nolan which was nominated for 5 Oscars and won Best Visual Effects.' },
        { word: 'MATRIX', trivia: 'The code in The Matrix comes from sushi recipes.' },
        { word: 'GODFATHER', trivia: 'The cat held by Marlon Brando in the opening scene was a stray found on the lot.' },
        { word: 'PARASITE', trivia: 'Parasite was the first non-English language film to win Best Picture at the Oscars.' },
        { word: 'FROZEN', trivia: 'Elsa was originally going to be the villain of Frozen.' },
        { word: 'UP', trivia: 'Up was the second animated film to be nominated for Best Picture.' },
        { word: 'COCO', trivia: 'Coco took six years to produce.' },
        { word: 'HAMILTON', trivia: 'Lin-Manuel Miranda wrote the first song for Hamilton on his honeymoon.' },
        { word: 'DUNE', trivia: 'Dune has been adapted for the screen three times.' },
        { word: 'TENET', trivia: 'Tenet features no green screen shots.' },
        { word: 'LOGAN', trivia: 'Logan was the first superhero movie to be nominated for Best Adapted Screenplay.' },
        { word: 'WHIPLASH', trivia: 'Whiplash was shot in just 19 days.' },
        { word: 'ALIEN', trivia: 'The slime used for the Alien was K-Y Jelly.' },
        { word: 'ROCKY', trivia: 'Sylvester Stallone wrote the script for Rocky in three and a half days.' },
        { word: 'JAWS', trivia: 'The mechanical shark in Jaws was named Bruce.' },
        { word: 'PULP FICTION', trivia: 'Pulp Fiction cost only $8.5 million to make.' },
        { word: 'FORREST GUMP', trivia: 'Tom Hanks was not paid for Forrest Gump, but took percentage points instead.' },
        { word: 'FIGHT CLUB', trivia: 'Brad Pitt and Edward Norton learned how to make soap for Fight Club.' },
        { word: 'GOODFELLAS', trivia: 'The "Funny how?" scene in Goodfellas was improvised.' },
        { word: 'SPIRITED AWAY', trivia: 'Spirited Away is the highest-grossing film in Japanese history.' },
        { word: 'THE LION KING', trivia: 'The Lion King was originally titled "King of the Jungle".' },
        { word: 'WALL-E', trivia: 'WALL-E was named after Walter Elias Disney.' },
        { word: 'TOY STORY', trivia: 'Toy Story was the first feature-length computer-animated film.' },
        { word: 'CASABLANCA', trivia: 'No one knew how Casablanca would end until the last days of shooting.' },
        { word: 'PSYCHO', trivia: 'Psycho was the first American film to show a toilet flushing.' },
        { word: 'VERTIGO', trivia: 'Vertigo introduced the "dolly zoom" camera effect.' },
        { word: 'CITIZEN KANE', trivia: 'Citizen Kane is often cited as the greatest film ever made.' },
        { word: 'SHAWSHANK', trivia: 'The Shawshank Redemption was a box office disappointment upon release.' },
        { word: 'SCHINDLER', trivia: 'Steven Spielberg refused to accept a salary for Schindler’s List.' },
        { word: 'APOCALYPSE NOW', trivia: 'Apocalypse Now took over three years to edit.' },
        { word: 'BLADE RUNNER', trivia: 'Blade Runner is based on the book "Do Androids Dream of Electric Sheep?".' },
        { word: 'MEMENTO', trivia: 'Memento is told in two different sequences of scenes: one in color, one in black and white.' },
        { word: 'PRESTIGE', trivia: 'The Prestige features David Bowie as Nikola Tesla.' },
        { word: 'DEPARTED', trivia: 'The Departed is a remake of the Hong Kong film "Infernal Affairs".' },
        { word: 'DARK KNIGHT', trivia: 'The Dark Knight was the first superhero movie to gross over $1 billion.' },
        { word: 'BATMAN', trivia: 'Batman was created by Bob Kane and Bill Finger.' },
        { word: 'SUPERMAN', trivia: 'Superman was the first superhero to get a feature film.' },
        { word: 'SPIDERMAN', trivia: 'Spider-Man was almost a horror movie directed by Tobe Hooper.' },
        { word: 'AVENGERS', trivia: 'The Avengers was the first Marvel movie to gross over $1 billion.' },
        { word: 'IRONMAN', trivia: 'Robert Downey Jr. improvised the line "I am Iron Man".' },
        { word: 'THOR', trivia: 'Tom Hiddleston originally auditioned for the role of Thor.' },
        { word: 'HULK', trivia: 'The Hulk was originally supposed to be grey.' },
        { word: 'WONDER WOMAN', trivia: 'Wonder Woman was created by the inventor of the lie detector test.' },
        { word: 'AQUAMAN', trivia: 'Aquaman is the highest-grossing DC film of all time.' },
        { word: 'BLACK PANTHER', trivia: 'Black Panther was the first superhero movie nominated for Best Picture.' },
        { word: 'CAPTAIN MARVEL', trivia: 'Captain Marvel was the first female-led MCU movie.' },
        { word: 'GUARDIANS', trivia: 'Vin Diesel recorded "I am Groot" over 1,000 times.' },
        { word: 'DEADPOOL', trivia: 'Deadpool was the highest-grossing R-rated movie until Joker.' },
        { word: 'WOLVERINE', trivia: 'Hugh Jackman has played Wolverine for 17 years.' },
        { word: 'JURASSIC PARK', trivia: 'The T-Rex roar in Jurassic Park was a mix of a baby elephant, a tiger, and an alligator.' },
        { word: 'STAR WARS', trivia: 'Yoda was almost played by a monkey.' },
        { word: 'BACK TO THE FUTURE', trivia: 'The time machine was originally going to be a refrigerator.' },
        { word: 'INDIANA JONES', trivia: 'Indiana Jones was named after George Lucas’s dog.' },
        { word: 'TERMINATOR', trivia: 'O.J. Simpson was considered for the role of the Terminator.' },
        { word: 'GHOSTBUSTERS', trivia: 'The phone number in Ghostbusters was a real working number.' },
        { word: 'ET', trivia: 'E.T.’s face was modeled after Albert Einstein, Carl Sandburg, and a pug.' },
        { word: 'HOME ALONE', trivia: 'The photo of Buzz’s girlfriend was actually a boy in a wig.' },
        { word: 'SHREK', trivia: 'Shrek was originally voiced by Chris Farley before he passed away.' },
        { word: 'FINDING NEMO', trivia: 'Finding Nemo is the best-selling DVD of all time.' }
    ],
    'Science': [
        { word: 'GRAVITY', trivia: 'Gravity is the force that attracts a body toward the center of the earth.' },
        { word: 'ATOM', trivia: 'Atoms are mostly empty space.' },
        { word: 'NEURON', trivia: 'The human brain has approximately 86 billion neurons.' },
        { word: 'GALAXY', trivia: 'The Milky Way galaxy is about 100,000 light-years across.' },
        { word: 'PHYSICS', trivia: 'Physics is the natural science that studies matter and energy.' },
        { word: 'QUANTUM', trivia: 'Quantum mechanics deals with the behavior of matter and light on the atomic scale.' },
        { word: 'ORBIT', trivia: 'The Moon orbits the Earth every 27.3 days.' },
        { word: 'FOSSIL', trivia: 'Fossils are the preserved remains of ancient organisms.' },
        { word: 'VIRUS', trivia: 'Viruses are not considered living organisms by many biologists.' },
        { word: 'ROBOT', trivia: 'The word "robot" comes from the Czech word for forced labor.' },
        { word: 'ENERGY', trivia: 'Energy cannot be created or destroyed, only transformed.' },
        { word: 'LASER', trivia: 'LASER stands for Light Amplification by Stimulated Emission of Radiation.' },
        { word: 'PRISM', trivia: 'A prism breaks light into its constituent spectral colors.' },
        { word: 'MAGNET', trivia: 'Magnets have two poles: North and South.' },
        { word: 'CLONE', trivia: 'Dolly the sheep was the first mammal cloned from an adult somatic cell.' },
        { word: 'DNA', trivia: 'DNA contains the genetic instructions for the development of all known living organisms.' },
        { word: 'CELL', trivia: 'The cell is the basic structural and functional unit of life.' },
        { word: 'ACID', trivia: 'Acids have a pH less than 7.' },
        { word: 'BASE', trivia: 'Bases have a pH greater than 7.' },
        { word: 'WAVE', trivia: 'Sound waves cannot travel through a vacuum.' },
        { word: 'ECLIPSE', trivia: 'A solar eclipse occurs when the Moon passes between the Earth and the Sun.' },
        { word: 'TELESCOPE', trivia: 'The Hubble Space Telescope was launched in 1990.' },
        { word: 'MICROSCOPE', trivia: 'Microscopes allow us to see objects that are too small for the naked eye.' },
        { word: 'BACTERIA', trivia: 'There are more bacteria in your mouth than there are people in the world.' },
        { word: 'VACCINE', trivia: 'The first vaccine was developed for smallpox.' },
        { word: 'SATELLITE', trivia: 'The Moon is Earth’s only natural satellite.' },
        { word: 'ASTEROID', trivia: 'Most asteroids orbit the Sun in the asteroid belt between Mars and Jupiter.' },
        { word: 'COMET', trivia: 'Comets are cosmic snowballs of frozen gases, rock, and dust.' },
        { word: 'MOLECULE', trivia: 'A molecule is a group of atoms bonded together.' },
        { word: 'ELECTRON', trivia: 'Electrons have a negative electric charge.' },
        { word: 'PROTON', trivia: 'Protons have a positive electric charge.' },
        { word: 'NEUTRON', trivia: 'Neutrons have no electric charge.' },
        { word: 'PHOTON', trivia: 'A photon is a particle of light.' },
        { word: 'PLASMA', trivia: 'Plasma is the fourth state of matter.' },
        { word: 'CRYSTAL', trivia: 'Crystals have a highly ordered microscopic structure.' },
        { word: 'ENZYME', trivia: 'Enzymes are biological catalysts.' },
        { word: 'PROTEIN', trivia: 'Proteins are large biomolecules and macromolecules.' },
        { word: 'CARBON', trivia: 'Carbon is the chemical basis for all known life.' },
        { word: 'OXYGEN', trivia: 'Oxygen makes up about 21% of Earth’s atmosphere.' },
        { word: 'HYDROGEN', trivia: 'Hydrogen is the most abundant chemical substance in the universe.' },
        { word: 'NITROGEN', trivia: 'Nitrogen makes up about 78% of Earth’s atmosphere.' },
        { word: 'HELIUM', trivia: 'Helium is the second lightest and second most abundant element.' },
        { word: 'SODIUM', trivia: 'Sodium is a soft, silvery-white, highly reactive metal.' },
        { word: 'CALCIUM', trivia: 'Calcium is essential for living organisms, particularly in cell physiology.' },
        { word: 'IRON', trivia: 'Iron is the most common element on Earth by mass.' },
        { word: 'COPPER', trivia: 'Copper was the first metal to be used by humans.' },
        { word: 'SPECTRUM', trivia: 'The visible spectrum is the portion of the electromagnetic spectrum that is visible to the human eye.' },
        { word: 'RADIATION', trivia: 'Radiation is the emission or transmission of energy in the form of waves or particles.' },
        { word: 'FRICTION', trivia: 'Friction is the force resisting the relative motion of solid surfaces.' },
        { word: 'MOMENTUM', trivia: 'Momentum is the product of the mass and velocity of an object.' },
        { word: 'VELOCITY', trivia: 'Velocity is the speed of an object in a given direction.' },
        { word: 'ACCELERATION', trivia: 'Acceleration is the rate of change of velocity.' },
        { word: 'FORCE', trivia: 'Force is any interaction that, when unopposed, will change the motion of an object.' },
        { word: 'PRESSURE', trivia: 'Pressure is the force applied perpendicular to the surface of an object.' },
        { word: 'VOLUME', trivia: 'Volume is the quantity of three-dimensional space enclosed by a closed surface.' },
        { word: 'EVOLUTION', trivia: 'Charles Darwin proposed the theory of evolution by natural selection.' },
        { word: 'PHOTOSYNTHESIS', trivia: 'Photosynthesis is the process used by plants to convert light energy into chemical energy.' },
        { word: 'ECOSYSTEM', trivia: 'An ecosystem is a community of living organisms in conjunction with the nonliving components of their environment.' },
        { word: 'BIOLOGY', trivia: 'Biology is the natural science that studies life and living organisms.' },
        { word: 'CHEMISTRY', trivia: 'Chemistry is the scientific discipline involved with elements and compounds.' },
        { word: 'ASTRONOMY', trivia: 'Astronomy is the study of celestial objects and phenomena.' },
        { word: 'GEOLOGY', trivia: 'Geology is an earth science concerned with the solid Earth.' },
        { word: 'METEOR', trivia: 'A meteor is a meteoroid that has entered Earth’s atmosphere.' },
        { word: 'BLACK HOLE', trivia: 'A black hole is a region of spacetime where gravity is so strong that nothing can escape.' },
        { word: 'SUPERNOVA', trivia: 'A supernova is a powerful and luminous stellar explosion.' }
    ],
    'Celebrities': [
        { word: 'BEYONCE', trivia: 'Beyoncé is the most awarded female artist in Grammy history.' },
        { word: 'DRAKE', trivia: 'Drake has the most Billboard Hot 100 entries of any artist.' },
        { word: 'RIHANNA', trivia: 'Rihanna is the richest female musician in the world.' },
        { word: 'EMINEM', trivia: 'Eminem’s "Rap God" holds the Guinness World Record for most words in a hit single.' },
        { word: 'ADELE', trivia: 'Adele’s album "21" is the best-selling album of the 21st century.' },
        { word: 'ZENDAYA', trivia: 'Zendaya is the youngest woman to win the Emmy for Best Lead Actress in a Drama.' },
        { word: 'ROCK', trivia: 'Dwayne "The Rock" Johnson was a professional wrestler before becoming an actor.' },
        { word: 'OPRAH', trivia: 'Oprah Winfrey was the first black female billionaire.' },
        { word: 'ELVIS', trivia: 'Elvis Presley is the best-selling solo music artist of all time.' },
        { word: 'PRINCE', trivia: 'Prince wrote his first song at age seven.' },
        { word: 'MADONNA', trivia: 'Madonna is the best-selling female recording artist of all time.' },
        { word: 'CHER', trivia: 'Cher is known as the "Goddess of Pop".' },
        { word: 'BONO', trivia: 'Bono is the lead vocalist of the rock band U2.' },
        { word: 'STING', trivia: 'Sting was the lead singer of The Police.' },
        { word: 'USHER', trivia: 'Usher was discovered on Star Search at age 13.' },
        { word: 'SHAKIRA', trivia: 'Shakira is the highest-selling Colombian artist of all time.' },
        { word: 'PINK', trivia: 'Pink was a gymnast for eight years.' },
        { word: 'SEAL', trivia: 'Seal is known for his hit song "Kiss from a Rose".' },
        { word: 'BECK', trivia: 'Beck plays over 10 instruments.' },
        { word: 'ENYA', trivia: 'Enya is Ireland’s best-selling solo artist.' },
        { word: 'TAYLOR SWIFT', trivia: 'Taylor Swift is the only artist to win the Grammy for Album of the Year four times.' },
        { word: 'KANYE WEST', trivia: 'Kanye West has won 24 Grammy Awards.' },
        { word: 'LADY GAGA', trivia: 'Lady Gaga’s real name is Stefani Joanne Angelina Germanotta.' },
        { word: 'JUSTIN BIEBER', trivia: 'Justin Bieber was discovered on YouTube.' },
        { word: 'ARIANA GRANDE', trivia: 'Ariana Grande began her career in the Broadway musical 13.' },
        { word: 'BRUNO MARS', trivia: 'Bruno Mars’ real name is Peter Gene Hernandez.' },
        { word: 'ED SHEERAN', trivia: 'Ed Sheeran names his guitars.' },
        { word: 'MICHAEL JACKSON', trivia: 'Michael Jackson’s "Thriller" is the best-selling album of all time.' },
        { word: 'WHITNEY HOUSTON', trivia: 'Whitney Houston is the most awarded female artist of all time.' },
        { word: 'MARIAH CAREY', trivia: 'Mariah Carey has a five-octave vocal range.' },
        { word: 'CELINE DION', trivia: 'Celine Dion won Eurovision in 1988 representing Switzerland.' },
        { word: 'BRITNEY SPEARS', trivia: 'Britney Spears is known as the "Princess of Pop".' },
        { word: 'CHRISTINA AGUILERA', trivia: 'Christina Aguilera was a Mouseketeer.' },
        { word: 'JENNIFER LOPEZ', trivia: 'Jennifer Lopez was the first Latina actress to earn over $1 million for a film.' },
        { word: 'SELENA GOMEZ', trivia: 'Selena Gomez was the most followed person on Instagram for several years.' },
        { word: 'MILEY CYRUS', trivia: 'Miley Cyrus is the daughter of country singer Billy Ray Cyrus.' },
        { word: 'KATY PERRY', trivia: 'Katy Perry has nine Billboard Hot 100 number-one singles.' },
        { word: 'DEMI LOVATO', trivia: 'Demi Lovato got her start on Barney & Friends.' },
        { word: 'BILLIE EILISH', trivia: 'Billie Eilish won five Grammys in 2020.' },
        { word: 'LIZZO', trivia: 'Lizzo is a classically trained flutist.' },
        { word: 'POST MALONE', trivia: 'Post Malone got his stage name from a rap name generator.' },
        { word: 'THE WEEKND', trivia: 'The Weeknd’s real name is Abel Makkonen Tesfaye.' },
        { word: 'HARRY STYLES', trivia: 'Harry Styles was a member of One Direction.' },
        { word: 'SHAWN MENDES', trivia: 'Shawn Mendes learned to play guitar by watching YouTube tutorials.' },
        { word: 'CAMILA CABELLO', trivia: 'Camila Cabello was a member of Fifth Harmony.' },
        { word: 'DUA LIPA', trivia: 'Dua Lipa worked as a model before becoming a singer.' },
        { word: 'OLIVIA RODRIGO', trivia: 'Olivia Rodrigo starred in High School Musical: The Musical: The Series.' },
        { word: 'TOM CRUISE', trivia: 'Tom Cruise does his own stunts.' },
        { word: 'WILL SMITH', trivia: 'Will Smith turned down the role of Neo in The Matrix.' },
        { word: 'LEONARDO DICAPRIO', trivia: 'Leonardo DiCaprio was named after Leonardo da Vinci.' },
        { word: 'BRAD PITT', trivia: 'Brad Pitt was banned from entering China for over 15 years.' },
        { word: 'ANGELINA JOLIE', trivia: 'Angelina Jolie has a pilot’s license.' },
        { word: 'JOHNNY DEPP', trivia: 'Johnny Depp has never won an Oscar.' },
        { word: 'MERYL STREEP', trivia: 'Meryl Streep has been nominated for a record 21 Academy Awards.' },
        { word: 'DENZEL WASHINGTON', trivia: 'Denzel Washington has won two Oscars.' },
        { word: 'MORGAN FREEMAN', trivia: 'Morgan Freeman didn’t get his big break until he was 50.' },
        { word: 'SAMUEL L JACKSON', trivia: 'Samuel L. Jackson is the highest-grossing actor of all time.' }
    ],
    'Politics': [
        { word: 'DEMOCRACY', trivia: 'Democracy originated in ancient Athens.' },
        { word: 'SENATE', trivia: 'The US Senate has 100 members.' },
        { word: 'VOTE', trivia: 'Women in the US gained the right to vote in 1920.' },
        { word: 'LIBERTY', trivia: 'The Statue of Liberty was a gift from France.' },
        { word: 'LAW', trivia: 'The Code of Hammurabi is one of the oldest deciphered writings of significant length in the world.' },
        { word: 'MAYOR', trivia: 'A mayor is the highest-ranking official in a municipal government.' },
        { word: 'VETO', trivia: 'Veto is Latin for "I forbid".' },
        { word: 'BILL', trivia: 'A bill becomes a law after it is passed by the legislature and signed by the executive.' },
        { word: 'POLL', trivia: 'Exit polls are taken immediately after voters have left the polling stations.' },
        { word: 'TERM', trivia: 'The US President serves a four-year term.' },
        { word: 'RIGHTS', trivia: 'The Bill of Rights consists of the first ten amendments to the US Constitution.' },
        { word: 'DUTY', trivia: 'Jury duty is a mandatory civic service.' },
        { word: 'TAX', trivia: 'The IRS collects federal taxes in the US.' },
        { word: 'PACT', trivia: 'A pact is a formal agreement between individuals or parties.' },
        { word: 'ALLY', trivia: 'The US and UK have been close allies for over a century.' },
        { word: 'WAR', trivia: 'The longest war in history lasted 335 years.' },
        { word: 'PEACE', trivia: 'The Nobel Peace Prize is awarded annually in Oslo, Norway.' },
        { word: 'FLAG', trivia: 'The US flag has 50 stars and 13 stripes.' },
        { word: 'OATH', trivia: 'The Presidential Oath of Office is 35 words long.' },
        { word: 'SEAT', trivia: 'There are 435 seats in the US House of Representatives.' },
        { word: 'PARLIAMENT', trivia: 'The British Parliament is the "Mother of Parliaments".' },
        { word: 'CONGRESS', trivia: 'The US Congress meets in the Capitol building.' },
        { word: 'ELECTION', trivia: 'US Presidential elections are held on the first Tuesday after the first Monday in November.' },
        { word: 'BALLOT', trivia: 'The secret ballot was first used in Australia.' },
        { word: 'CAMPAIGN', trivia: 'Presidential campaigns in the US can cost billions of dollars.' },
        { word: 'DEBATE', trivia: 'The first televised presidential debate was between Kennedy and Nixon.' },
        { word: 'POLICY', trivia: 'Foreign policy dictates how a country interacts with other nations.' },
        { word: 'TREATY', trivia: 'The Treaty of Versailles ended World War I.' },
        { word: 'CONSTITUTION', trivia: 'The US Constitution is the oldest written national constitution in operation.' },
        { word: 'AMENDMENT', trivia: 'There are 27 amendments to the US Constitution.' },
        { word: 'JUSTICE', trivia: 'The Supreme Court is the highest court in the US.' },
        { word: 'COURT', trivia: 'There are 9 Justices on the US Supreme Court.' },
        { word: 'JUDGE', trivia: 'Federal judges are appointed for life.' },
        { word: 'JURY', trivia: 'A standard criminal jury consists of 12 jurors.' },
        { word: 'VERDICT', trivia: 'A verdict must be unanimous in most criminal cases.' },
        { word: 'APPEAL', trivia: 'An appeal is a request for a higher court to review a decision.' },
        { word: 'STATUTE', trivia: 'A statute is a written law passed by a legislative body.' },
        { word: 'GOVERNOR', trivia: 'A governor is the head of a state government.' },
        { word: 'PRESIDENT', trivia: 'George Washington was the first US President.' },
        { word: 'MINISTER', trivia: 'A prime minister is the head of government in a parliamentary system.' },
        { word: 'DIPLOMAT', trivia: 'Diplomats represent their country abroad.' },
        { word: 'EMBASSY', trivia: 'An embassy is the official residence of an ambassador.' },
        { word: 'CONSUL', trivia: 'A consul assists citizens of their own country in a foreign city.' },
        { word: 'SUMMIT', trivia: 'A summit is a meeting between heads of government.' },
        { word: 'COALITION', trivia: 'A coalition government is formed by multiple parties.' },
        { word: 'REFERENDUM', trivia: 'Brexit was decided by a referendum.' },
        { word: 'IMPEACHMENT', trivia: 'Three US Presidents have been impeached.' },
        { word: 'CABINET', trivia: 'The Cabinet advises the President.' },
        { word: 'LEGISLATURE', trivia: 'The legislature makes laws.' },
        { word: 'EXECUTIVE', trivia: 'The executive branch enforces laws.' },
        { word: 'JUDICIAL', trivia: 'The judicial branch interprets laws.' },
        { word: 'FEDERAL', trivia: 'The US has a federal system of government.' },
        { word: 'STATE', trivia: 'There are 50 states in the US.' },
        { word: 'MUNICIPAL', trivia: 'Municipal governments run cities and towns.' },
        { word: 'DICTATOR', trivia: 'Julius Caesar was appointed dictator for life.' },
        { word: 'MONARCHY', trivia: 'The United Kingdom is a constitutional monarchy.' },
        { word: 'REPUBLIC', trivia: 'A republic is a form of government where the country is considered a "public matter".' },
        { word: 'ANARCHY', trivia: 'Anarchy is a society without a publicly enforced government.' },
        { word: 'OLIGARCHY', trivia: 'An oligarchy is a form of power structure in which power rests with a small number of people.' },
        { word: 'THEOCRACY', trivia: 'A theocracy is a form of government in which a deity of some type is recognized as the supreme ruling authority.' },
        { word: 'AUTOCRACY', trivia: 'An autocracy is a system of government by one person with absolute power.' },
        { word: 'SOCIALISM', trivia: 'Socialism is a political, social, and economic philosophy encompassing a range of economic and social systems.' },
        { word: 'COMMUNISM', trivia: 'Communism is a philosophical, social, political, and economic ideology and movement.' },
        { word: 'CAPITALISM', trivia: 'Capitalism is an economic system based on the private ownership of the means of production.' }
    ],
    'Geography': [
        { word: 'AMAZON', trivia: 'The Amazon Rainforest produces 20% of the world’s oxygen.' },
        { word: 'SAHARA', trivia: 'The Sahara is the largest hot desert in the world.' },
        { word: 'EVEREST', trivia: 'Mount Everest is the highest mountain above sea level.' },
        { word: 'NILE', trivia: 'The Nile is traditionally considered the longest river in the world.' },
        { word: 'CANYON', trivia: 'The Grand Canyon is over a mile deep.' },
        { word: 'ANDES', trivia: 'The Andes is the longest continental mountain range in the world.' },
        { word: 'ALPS', trivia: 'The Alps are the highest and most extensive mountain range system in Europe.' },
        { word: 'FIJI', trivia: 'Fiji is an archipelago of more than 330 islands.' },
        { word: 'PERU', trivia: 'Machu Picchu is located in Peru.' },
        { word: 'ROME', trivia: 'Rome contains a sovereign state, Vatican City, within its borders.' },
        { word: 'TOKYO', trivia: 'Tokyo is the most populous metropolitan area in the world.' },
        { word: 'PARIS', trivia: 'The Eiffel Tower was originally intended to be temporary.' },
        { word: 'OSLO', trivia: 'Oslo is the capital of Norway.' },
        { word: 'LIMA', trivia: 'Lima is the second largest desert city in the world after Cairo.' },
        { word: 'JAVA', trivia: 'Java is the most populous island in the world.' },
        { word: 'BALI', trivia: 'Bali is known as the "Island of the Gods".' },
        { word: 'CUBA', trivia: 'Cuba is the largest island in the Caribbean.' },
        { word: 'IRAN', trivia: 'Iran was historically known as Persia.' },
        { word: 'IRAQ', trivia: 'Ancient Mesopotamia was located in modern-day Iraq.' },
        { word: 'OHIO', trivia: 'Ohio is known as the "Buckeye State".' },
        { word: 'LONDON', trivia: 'London has over 170 museums.' },
        { word: 'BERLIN', trivia: 'Berlin has more bridges than Venice.' },
        { word: 'MADRID', trivia: 'Madrid is the highest capital city in Europe.' },
        { word: 'MOSCOW', trivia: 'Moscow has the busiest metro system in Europe.' },
        { word: 'BEIJING', trivia: 'Beijing is home to seven UNESCO World Heritage Sites.' },
        { word: 'SYDNEY', trivia: 'The Sydney Opera House was designed by a Danish architect.' },
        { word: 'CAIRO', trivia: 'Cairo is home to the only remaining Ancient Wonder of the World.' },
        { word: 'DUBAI', trivia: 'Dubai is home to the world’s tallest building, the Burj Khalifa.' },
        { word: 'ICELAND', trivia: 'Iceland has no standing army.' },
        { word: 'IRELAND', trivia: 'St. Patrick was actually British, not Irish.' },
        { word: 'SCOTLAND', trivia: 'Scotland has approximately 790 islands.' },
        { word: 'WALES', trivia: 'Wales has more castles per square mile than any other country.' },
        { word: 'DENMARK', trivia: 'Denmark is home to the oldest monarchy in Europe.' },
        { word: 'SWEDEN', trivia: 'Sweden imports waste from other countries to power its energy plants.' },
        { word: 'NORWAY', trivia: 'Norway introduced salmon sushi to Japan.' },
        { word: 'FINLAND', trivia: 'Finland has the most heavy metal bands per capita.' },
        { word: 'POLAND', trivia: 'Poland has the world’s biggest castle by land area.' },
        { word: 'AUSTRIA', trivia: 'Austria is the birthplace of Mozart.' },
        { word: 'SWITZERLAND', trivia: 'Switzerland has four official languages.' },
        { word: 'BELGIUM', trivia: 'Belgium produces over 220,000 tons of chocolate per year.' },
        { word: 'NETHERLANDS', trivia: 'There are more bicycles than people in the Netherlands.' },
        { word: 'PORTUGAL', trivia: 'Portugal is the oldest country in Europe with defined borders.' },
        { word: 'GREECE', trivia: 'Greece has thousands of islands, but only about 200 are inhabited.' },
        { word: 'TURKEY', trivia: 'Istanbul is the only city in the world located on two continents.' },
        { word: 'EGYPT', trivia: 'The Great Pyramid of Giza was the tallest man-made structure for over 3,800 years.' },
        { word: 'MOROCCO', trivia: 'The oldest university in the world is in Morocco.' },
        { word: 'KENYA', trivia: 'Kenya is home to the "Big Five" game animals.' },
        { word: 'NIGERIA', trivia: 'Nigeria is the most populous country in Africa.' },
        { word: 'GHANA', trivia: 'Lake Volta in Ghana is the largest man-made lake in the world.' },
        { word: 'ETHIOPIA', trivia: 'Ethiopia is the only African country never colonized.' },
        { word: 'TANZANIA', trivia: 'Mount Kilimanjaro is in Tanzania.' },
        { word: 'UGANDA', trivia: 'Uganda is known as the "Pearl of Africa".' },
        { word: 'ZIMBABWE', trivia: 'Victoria Falls is located on the border of Zimbabwe and Zambia.' },
        { word: 'BOTSWANA', trivia: 'Botswana is home to the world’s largest concentration of African elephants.' },
        { word: 'NAMIBIA', trivia: 'The Namib Desert is considered the oldest desert in the world.' },
        { word: 'CANADA', trivia: 'Canada has the longest coastline of any country in the world.' },
        { word: 'MEXICO', trivia: 'Mexico City is sinking at a rate of 10 inches per year.' },
        { word: 'BRAZIL', trivia: 'Brazil is the largest coffee producer in the world.' },
        { word: 'ARGENTINA', trivia: 'Argentina is the birthplace of the tango.' },
        { word: 'CHILE', trivia: 'Chile is home to the driest place on Earth, the Atacama Desert.' },
        { word: 'AUSTRALIA', trivia: 'Australia is the only continent covered by a single country.' },
        { word: 'NEW ZEALAND', trivia: 'New Zealand was the first country to give women the vote.' },
        { word: 'INDIA', trivia: 'India has the largest postal network in the world.' },
        { word: 'THAILAND', trivia: 'Thailand is the only Southeast Asian country never colonized by a European power.' },
        { word: 'VIETNAM', trivia: 'Vietnam is the second largest coffee producer in the world.' }
    ],
    'History': [
        { word: 'VIKING', trivia: 'Vikings used onion soup to gauge the depth of wounds.' },
        { word: 'SPARTAN', trivia: 'Spartan men were required to serve in the military until age 60.' },
        { word: 'SAMURAI', trivia: 'Samurai were the military nobility and officer caste of medieval and early-modern Japan.' },
        { word: 'KNIGHT', trivia: 'Knights were expected to follow a code of chivalry.' },
        { word: 'PHARAOH', trivia: 'Pharaohs were considered to be half-man, half-god.' },
        { word: 'EMPEROR', trivia: 'The Roman Empire lasted for over 1000 years.' },
        { word: 'PYRAMID', trivia: 'The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World.' },
        { word: 'CASTLE', trivia: 'Castles were built to defend against attacks.' },
        { word: 'MUMMY', trivia: 'Ancient Egyptians mummified their dead to preserve them for the afterlife.' },
        { word: 'GLADIATOR', trivia: 'Gladiators were often slaves or prisoners of war.' },
        { word: 'CRUSADE', trivia: 'The Crusades were a series of religious wars initiated, supported, and sometimes directed by the Latin Church.' },
        { word: 'REVOLUTION', trivia: 'The French Revolution led to the rise of Napoleon Bonaparte.' },
        { word: 'COLONY', trivia: 'The 13 American colonies declared independence from Britain in 1776.' },
        { word: 'EMPIRE', trivia: 'The British Empire was the largest empire in history.' },
        { word: 'DYNASTY', trivia: 'The Ming Dynasty ruled China for 276 years.' },
        { word: 'TRENCH', trivia: 'Trench warfare was a defining characteristic of World War I.' },
        { word: 'BUNKER', trivia: 'Bunkers are defensive military fortifications designed to protect people and valued materials.' },
        { word: 'TREATY', trivia: 'The Treaty of Versailles officially ended World War I.' },
        { word: 'ALLIANCE', trivia: 'NATO is a military alliance between 30 North American and European countries.' },
        { word: 'DICTATOR', trivia: 'Adolf Hitler was the dictator of Nazi Germany.' },
        { word: 'PRESIDENT', trivia: 'Abraham Lincoln was the 16th President of the United States.' },
        { word: 'GENERAL', trivia: 'George Washington was a general in the Continental Army.' },
        { word: 'ADMIRAL', trivia: 'Horatio Nelson was a British flag officer in the Royal Navy.' },
        { word: 'SOLDIER', trivia: 'Soldiers have fought in wars throughout history.' },
        { word: 'WARRIOR', trivia: 'Warriors are people specializing in combat or warfare.' },
        { word: 'LEGEND', trivia: 'Legends are stories about human events or actions that have not been proved nor documented.' },
        { word: 'MYTH', trivia: 'Myths are traditional stories, especially one concerning the early history of a people.' },
        { word: 'ARTIFACT', trivia: 'Artifacts are objects made by a human being, typically an item of cultural or historical interest.' },
        { word: 'RUINS', trivia: 'Ruins are the remains of a building, city, etc., that has been destroyed or that is in a state of decay.' },
        { word: 'TEMPLE', trivia: 'Temples are structures reserved for religious or spiritual rituals.' },
        { word: 'TOMB', trivia: 'The Taj Mahal is a tomb built by Emperor Shah Jahan for his favorite wife.' },
        { word: 'THRONE', trivia: 'The Iron Throne is a fictional throne in the A Song of Ice and Fire series.' },
        { word: 'CROWN', trivia: 'The Crown Jewels of the United Kingdom are kept in the Tower of London.' },
        { word: 'SCEPTRE', trivia: 'A sceptre is a symbolic ornamental staff or wand held in the hand by a ruling monarch.' },
        { word: 'SHIELD', trivia: 'Shields were used to protect soldiers from enemy attacks.' },
        { word: 'SWORD', trivia: 'Swords have been used in warfare for thousands of years.' },
        { word: 'ARMOR', trivia: 'Armor was used to protect the body from injury in combat.' },
        { word: 'CHARIOT', trivia: 'Chariots were used in warfare and racing in ancient times.' },
        { word: 'CATAPULT', trivia: 'Catapults were used to launch projectiles at enemy fortifications.' },
        { word: 'CANNON', trivia: 'Cannons were used in warfare from the late Middle Ages onwards.' },
        { word: 'MUSKET', trivia: 'Muskets were used by infantry soldiers from the 16th to the 19th century.' },
        { word: 'PISTOL', trivia: 'Pistols are small handguns designed to be held in one hand.' },
        { word: 'RIFLE', trivia: 'Rifles are long-barreled firearms designed for accurate shooting.' },
        { word: 'TANK', trivia: 'Tanks were first used in battle during World War I.' },
        { word: 'PLANE', trivia: 'The Wright brothers invented the first successful airplane.' },
        { word: 'SHIP', trivia: 'Ships have been used for exploration, trade, and warfare for thousands of years.' },
        { word: 'SUBMARINE', trivia: 'Submarines were first used in warfare during the American Civil War.' },
        { word: 'ROCKET', trivia: 'Rockets were invented in China in the 13th century.' },
        { word: 'BOMB', trivia: 'The atomic bomb was developed during World War II.' },
        { word: 'PEACE', trivia: 'Peace is a state of tranquility or quiet.' }
    ]
};
